[build]
builder = "DOCKERFILE"
dockerfilePath = "dockerfile"

[deploy]
startCommand = "python manage.py collectstatic --noinput --clear && daphne -b 0.0.0.0 -p $PORT WearableApi.asgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
